
CC			=	gcc
# CFLAGS		=	-Wall -Werror -Wextra -fsanitize=address
CFLAGS		=	-Wall -Werror -Wextra


all		:
	@$(CC) $(CFLAGS) -o test0 ./test0.c
	@$(CC) $(CFLAGS) -o test1 ./test1.c
	

fclean	:
	rm test0
	rm test1